# Matrix Multiplication

torch에는 같은 연산을 수행하지만 다양한 행렬곱 함수가 존재한다.

In [1]:
import torch
import torch.nn as nn

A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)


1. `torch.matmul()`

In [6]:
C = torch.matmul(A,B)
print(C)

tensor([[19., 22.],
        [43., 50.]])


2. `@` 연산자

`torch.matmul()`과 동일한 기능을 수행한다.

In [7]:
C = A @ B
print(C)

tensor([[19., 22.],
        [43., 50.]])


3. `torch.einsum()`

아인슈타인 합 규칙을 기반으로 행렬 곱셈 및 더 복잡한 연산을 수행할 수 있는 유연한 함수이다.

In [9]:
C = torch.einsum('ij,jk->ik', A, B)
print(D)

tensor([[19., 22.],
        [43., 50.]])


# Linear Layer is Matrix Multiplication

Linear Layer 또한 하나의 행렬 곱으로 이해할 수 있다.<br>
둘이 동일함을 코드로 확인하겠다.

In [15]:
batch_size = 32
seq_len = 512
n_dim = 768
output_dim = n_dim * 3

X = torch.randn(batch_size, seq_len, n_dim) # (32, 512, 768)
ln = nn.Linear(n_dim, output_dim) 

In [16]:
ln_out = ln(X)
ln_out.shape

torch.Size([32, 512, 2304])

In [17]:
weight = ln.weight
bias = ln.bias
matrix_out = X @ weight.t() + bias
matrix_out.shape

torch.Size([32, 512, 2304])

In [18]:
torch.allclose(ln_out, matrix_out, atol=1e-6)

True