view는 비연속적은 contiguos()처리를 해야함
비연속적인 경우
1. transpose 하는 경우
2. slicing으로 배열에 재할당하는경우 // sliced_tensor = tensor[:, 1:]
3. permute로 차원 바꾸는 거

view 함수를 사용하여 텐서의 모양을 변경할 때, 텐서의 요소들은 메모리 저장 순서에 따라 새로운 모양으로 재배치됩니다. 

메모리 저장 순서란, 텐서가 메모리에 연속적으로 저장된 순서를 의미합니다

In [1]:
import torch

t = torch.arange(24).view(1,2,3,4)
t

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])

In [6]:
t2 = torch.arange(1,13).view(3,2,2)
print(t2)
t3 = t2.permute(1,0,2)
print(t3)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
tensor([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],

        [[ 3,  4],
         [ 7,  8],
         [11, 12]]])


In [8]:
# Permute랑 view는 다름

t = torch.arange(1,13).reshape(3,4)

t_view = t.view(4,3)
t_perm = t.permute(1,0)

print(t)
print(t_view)
print(t_perm)


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [11]:
t = torch.arange(1,25).view(4,2,3)
print(t)

print(t.permute(1,0,2))



tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
tensor([[[ 1,  2,  3],
         [ 7,  8,  9],
         [13, 14, 15],
         [19, 20, 21]],

        [[ 4,  5,  6],
         [10, 11, 12],
         [16, 17, 18],
         [22, 23, 24]]])


In [4]:
PyTorch에서 텐서가 메모리에 저장되는 순서는 C-주도(C-order) 또는 행우선(row-major) 순서라고 합니다. 이는 가장 마지막 차원부터 순차적으로 메모리에 저장된다는 의미입니다.

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])